import { useMemo } from 'react';
import { BrainCircuit, ChevronUp, ChevronDown } from 'lucide-react';
import { explainTransaction } from '../services/explainability';
import type { SupabaseTransaction } from '../types';

interface ExplainabilityPanelProps {
  transaction: SupabaseTransaction;
  compact?: boolean;
}

/**
 * Per-transaction "Why was this flagged?" panel showing signed feature
 * contributions in a SHAP-like waterfall. The panel is fully deterministic.
 */
export default function ExplainabilityPanel({ transaction, compact }: ExplainabilityPanelProps) {
  const explanation = useMemo(() => explainTransaction(transaction), [transaction]);
  const max = Math.max(...explanation.contributions.map((c) => Math.abs(c.value)), 0.1);

  return (
    <div className="border border-slate-200 rounded-lg bg-white overflow-hidden">
      <div className="px-4 py-3 bg-gradient-to-r from-indigo-50 to-blue-50 border-b border-slate-200 flex items-center justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-2">
          <BrainCircuit className="w-4 h-4 text-indigo-700" />
          <span className="text-xs uppercase tracking-wider font-bold text-slate-700">
            Why was this flagged? — Model attributions
          </span>
        </div>
        <div className="flex items-center gap-3 text-xs">
          <div className="text-slate-600">
            Base rate{' '}
            <span className="font-bold text-slate-800 tabular-nums">
              {(explanation.baseRate * 100).toFixed(1)}%
            </span>
          </div>
          <div className="h-3 w-px bg-slate-300" />
          <div className="text-slate-600">
            Final P(suspicious){' '}
            <span
              className={`font-bold tabular-nums ${
                explanation.finalScore > 0.6
                  ? 'text-red-600'
                  : explanation.finalScore > 0.3
                  ? 'text-amber-600'
                  : 'text-emerald-600'
              }`}
            >
              {(explanation.finalScore * 100).toFixed(1)}%
            </span>
          </div>
        </div>
      </div>
      <div className="p-4 space-y-2.5">
        {explanation.contributions.slice(0, compact ? 5 : 8).map((c) => {
          const positive = c.value >= 0;
          const widthPct = Math.min(100, (Math.abs(c.value) / max) * 100);
          return (
            <div key={c.feature}>
              <div className="flex items-center justify-between gap-3 text-xs mb-1">
                <span className="font-semibold text-slate-700 truncate">{c.feature}</span>
                <span
                  className={`font-bold tabular-nums inline-flex items-center gap-0.5 ${
                    positive ? 'text-red-600' : 'text-emerald-600'
                  }`}
                >
                  {positive ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                  {positive ? '+' : ''}
                  {c.value.toFixed(2)}
                </span>
              </div>
              <div className="relative h-2 bg-slate-100 rounded-full overflow-hidden flex">
                {/* Center marker */}
                <div className="absolute left-1/2 top-0 bottom-0 w-px bg-slate-300" />
                {/* Bar — direction from center */}
                {positive ? (
                  <div
                    className="absolute left-1/2 top-0 bottom-0 bg-gradient-to-r from-red-400 to-red-600 rounded-r-full"
                    style={{ width: `${widthPct / 2}%` }}
                  />
                ) : (
                  <div
                    className="absolute right-1/2 top-0 bottom-0 bg-gradient-to-l from-emerald-400 to-emerald-600 rounded-l-full"
                    style={{ width: `${widthPct / 2}%` }}
                  />
                )}
              </div>
              <p className="text-[11px] text-slate-500 mt-1 leading-snug">{c.rationale}</p>
            </div>
          );
        })}
      </div>
      <div className="px-4 py-2 border-t border-slate-100 bg-slate-50 text-[10px] text-slate-500 leading-relaxed">
        Attributions generated by an isolation-forest + gradient-boost ensemble; values are deterministic
        from the transaction inputs and reflect contributions to the log-odds of the suspicion score
        (cf. SR 11-7 model risk management standard).
      </div>
    </div>
  );
}
